AllCops:
  TargetRubyVersion: 2.4
  # Cop names are not d§splayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the -D/--display-cop-names
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding DisplayStyleGuide, or by giving the
  # -S/--display-style-guide option.
  DisplayStyleGuide: true
  # Excluded
  Exclude:
    - tmp/**/*
    - vendor/**/*
    - node_modules/**/*
    - db/*
    - config/**/*
    - bin/**
    - Gemfile
    - Gemfile.lock

Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 120
